name: Gerar JSONs de Detalhes

on:
  schedule:
    - cron: "0 */6 * * *" # a cada 6 horas
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install node-fetch@2

      - name: Rodar script de geração
        run: node scripts/build-detalhes.js

      - name: Commit e push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/fvs
          git commit -m "Atualiza JSONs de Detalhes [skip ci]" || echo "Sem alterações"
          git push
